using built in function to wait for dependencies, exit if dependency is not there.

diff --git a/absql b/absql
--- a/absql
+++ b/absql
@@ -8,30 +8,14 @@ set -e
 
 . /usr/local/etc/abenv
 
-#
-# check for linked dependencies
-#
-hosts=($(env | grep _TCP_ADDR | cut -d = -f 1))
-ports=($(env | grep _TCP_PORT | cut -d = -f 1))
-
-pl=$(for host in ${hosts[@]};
-do
-  port=$(echo $host | sed 's/_ADDR/_PORT/')
-  hosti=$(env | egrep ^$host | cut -d = -f 2)
-  porti=$(env | egrep ^$port | cut -d = -f 2)
-  echo $hosti:$porti
-done | sort -u)
-
-for p in $pl
-do
-  echo waiting for $p
-  while ! nc -w 1 $p 2>/dev/null
-  do
-    echo -n .
-    sleep 1
-  done
-  echo 'X'
-done
+# wait for dependencies, abort after 60 seconds
+waitforlink 60
+if [ $? -ne 0]
+then
+  echo 'Link with dependencies failed' >&2
+  # i don't know what happens here, maybe the compose tries it again?
+  exit 1
+fi
 
 cd ${PG_HOME}
 
